# Generated by Django 4.0.1 on 2022-01-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_market_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': 'market', 'verbose_name_plural': 'markets'},
        ),
    ]
